name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run unit test
        run: gradlew testDebugUnitTest
     
